import React from 'react'
import './dc.scss'

function DosECRUD() {
  return (
    <div className='dc'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum iure numquam doloribus est deleniti laudantium maxime omnis neque eum tempora beatae deserunt quod dolor aperiam ea, consectetur, ipsam animi aspernatur sit dignissimos aut. Delectus, temporibus mollitia repellat, quam beatae consequatur neque inventore necessitatibus perferendis dignissimos laborum nostrum doloremque sit facilis similique, asperiores molestiae eum doloribus! Perspiciatis velit dolore doloremque eius rerum unde optio cumque nihil, ex, ullam, soluta totam culpa atque corporis. Dolores, aperiam tenetur quo aliquid repudiandae ratione saepe provident debitis molestiae beatae, possimus ducimus enim nisi quae excepturi porro quos impedit minus ipsa eius explicabo ex cum mollitia ipsam! Iusto voluptatum suscipit adipisci iste laudantium voluptatibus numquam! Officiis excepturi maiores rem esse. Eos corrupti ad doloremque, nobis aliquid sint suscipit consequuntur aspernatur vel ipsum ratione quidem distinctio earum, tempore illo, voluptatibus nostrum veritatis laborum culpa autem delectus non. Quisquam distinctio deleniti praesentium possimus, vero debitis dolorum sequi voluptatem maxime minus adipisci molestias ex nihil inventore expedita tempore hic amet. Ea beatae a illo ut quae, quis porro enim sequi laudantium dolore nemo itaque perferendis numquam autem tempora modi? Placeat aperiam ullam vitae nisi voluptas repellendus neque praesentium consectetur at impedit reprehenderit dicta sequi, labore sunt voluptate eius autem necessitatibus illo delectus sed ex cupiditate. Itaque tenetur magnam cum minus necessitatibus nostrum ut unde quas corrupti ipsam corporis eaque in libero, maxime vel impedit quos, reprehenderit praesentium fugiat cupiditate dolorum! Similique eum et error minima doloremque impedit sequi atque odit omnis velit, assumenda ipsam animi ad, accusantium blanditiis asperiores labore. Magnam eum suscipit ab error consequatur perferendis repudiandae placeat, distinctio accusamus, fugiat, nulla maiores voluptatem recusandae esse facere ullam vel! Ipsum, tempore nostrum quasi libero quam ipsam eaque veniam corrupti velit deleniti distinctio totam sit, praesentium officiis? Sint voluptatibus vitae inventore minus nihil minima culpa nobis accusamus ut odio!</div>
  )
}

export default DosECRUD